services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_DB_USER}
      POSTGRES_PASSWORD: ${PG_DB_PASS}
      POSTGRES_DB: ${PG_DB}
      ENVIRONMENT: ${ENVIRONMENT:-Production}
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres_data_v1:/var/lib/postgresql/data

  api:
    restart: unless-stopped
    build:
      context: ./apps/middleware
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      PG_DB_USER: ${PG_DB_USER}
      PG_DB_PASS: ${PG_DB_PASS}
      PG_DB: ${PG_DB}
      PG_DB_HOST: db
      PG_DB_PORT: 5432
      ENVIRONMENT: ${ENVIRONMENT:-Production}
    volumes:
      - ./apps/middleware:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    working_dir: /app/apps/web
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: true
      ENVIRONMENT: ${ENVIRONMENT:-Production}
    command: npm run dev -- --host

  storybook:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    working_dir: /app/apps/web
    ports:
      - '6006:6006'
    depends_on:
      - web
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: true
      ENVIRONMENT: ${ENVIRONMENT:-Production}
    command: npm run storybook

volumes:
  postgres_data_v1:
