/*!
 * Copyright (C) Design:Funedikly. All rights reserved.
 */

export const States = {
  AL: { label: "AL", key: "al", name: "Alabama", dl_validation: "^d{7}$" },
  AK: { label: "AK", key: "ak", name: "Alaska", dl_validation: "^d{1,7}$" },
  AZ: {
    label: "AZ",
    key: "az",
    name: "Arizona",
    dl_validation: "^[aA-zZ]d{8}$",
  },
  AR: { label: "AR", key: "ar", name: "Arkansas", dl_validation: "^d{4,9}$" },
  CA: {
    label: "CA",
    key: "ca",
    name: "California",
    dl_validation: "^[aA-zZ]d{7}$",
  },
  CO: { label: "CO", key: "co", name: "Colorado", dl_validation: "^d{9}$" },
  CT: { label: "CT", key: "ct", name: "Connecticut", dl_validation: "^d{9}$" },
  DE: { label: "DE", key: "de", name: "Delaware", dl_validation: "^d{1,7}$" },
  FL: {
    label: "FL",
    key: "fl",
    name: "Florida",
    dl_validation: "^[aA-zZ]d{12}$",
  },
  GA: { label: "GA", key: "ga", name: "Georgia", dl_validation: "^d{7,9}$" },
  HI: { label: "HI", key: "hi", name: "Hawaii", dl_validation: "^d{8}$" },
  ID: {
    label: "ID",
    key: "id",
    name: "Idaho",
    dl_validation: "^[aA-zZ]{2}d{6}[aA-zZ]?$",
  },
  IL: {
    label: "IL",
    key: "il",
    name: "Illinois",
    dl_validation: "^[aA-zZ]d{11}$",
  },
  IN: { label: "IN", key: "in", name: "Indiana", dl_validation: "^d{9,10}$" },
  IA: { label: "IA", key: "ia", name: "Iowa", dl_validation: "^d{9}$" },
  KS: {
    label: "KS",
    key: "ks",
    name: "Kansas",
    dl_validation: "^[aA-zZ]{1,2}d{6,8}$",
  },
  KY: {
    label: "KY",
    key: "ky",
    name: "Kentucky",
    dl_validation: "^[aA-zZ]d{8}$",
  },
  LA: { label: "LA", key: "la", name: "Louisiana", dl_validation: "^d{1,9}$" },
  ME: { label: "ME", key: "me", name: "Maine", dl_validation: "^d{7}$" },
  MD: {
    label: "MD",
    key: "md",
    name: "Maryland",
    dl_validation: "^[aA-zZ]d{12}$",
  },
  MA: {
    label: "MA",
    key: "ma",
    name: "Massachusetts",
    dl_validation: "^d{9}$",
  },
  MI: {
    label: "MI",
    key: "mi",
    name: "Michigan",
    dl_validation: "^[aA-zZ]d{12}$",
  },
  MN: {
    label: "MN",
    key: "mn",
    name: "Minnesota",
    dl_validation: "^[aA-zZ]d{12}$",
  },
  MS: { label: "MS", key: "ms", name: "Mississippi", dl_validation: "^d{9}$" },
  MO: {
    label: "MO",
    key: "mo",
    name: "Missouri",
    dl_validation: "^[aA-zZ]d{5,9}$",
  },
  MT: { label: "MT", key: "mt", name: "Montana", dl_validation: "^d{13}$" },
  NE: {
    label: "NE",
    key: "ne",
    name: "Nebraska",
    dl_validation: "^[aA-zZ]d{6,8}$",
  },
  NV: { label: "NV", key: "nv", name: "Nevada", dl_validation: "^d{9,10}$" },
  NH: {
    label: "NH",
    key: "nh",
    name: "New Hampshire",
    dl_validation: "^d{2}[aA-zZ]{3}d{5}$",
  },
  NJ: {
    label: "NJ",
    key: "nj",
    name: "New Jersey",
    dl_validation: "^[aA-zZ]d{14}$",
  },
  NM: { label: "NM", key: "nm", name: "New Mexico", dl_validation: "^d{8,9}$" },
  NY: { label: "NY", key: "ny", name: "New York", dl_validation: "^d{9}$" },
  NC: {
    label: "NC",
    key: "nc",
    name: "North Carolina",
    dl_validation: "^d{1,12}$",
  },
  ND: {
    label: "ND",
    key: "nd",
    name: "North Dakota",
    dl_validation: "^[aA-zZ]{3}d{6}$",
  },
  OH: {
    label: "OH",
    key: "oh",
    name: "Ohio",
    dl_validation: "^[aA-zZ]{2}d{6}$",
  },
  OK: {
    label: "OK",
    key: "ok",
    name: "Oklahoma",
    dl_validation: "^[aA-zZ]d{9}$",
  },
  OR: { label: "OR", key: "or", name: "Oregon", dl_validation: "^d{1,9}$" },
  PA: { label: "PA", key: "pa", name: "Pennsylvania", dl_validation: "^d{8}$" },
  RI: { label: "RI", key: "ri", name: "Rhode Island", dl_validation: "^d{7}$" },
  SC: {
    label: "SC",
    key: "sc",
    name: "South Carolina",
    dl_validation: "^d{5,11}$",
  },
  SD: {
    label: "SD",
    key: "sd",
    name: "South Dakota",
    dl_validation: "^d{6,10}$",
  },
  TN: { label: "TN", key: "tn", name: "Tennessee", dl_validation: "^d{7,9}$" },
  TX: { label: "TX", key: "tx", name: "Texas", dl_validation: "^d{7,8}$" },
  UT: { label: "UT", key: "ut", name: "Utah", dl_validation: "^d{4,10}$" },
  VT: { label: "VT", key: "vt", name: "Vermont", dl_validation: "^d{8}$" },
  VA: {
    label: "VA",
    key: "va",
    name: "Virginia",
    dl_validation: "^[aA-zZ]d{8,11}$",
  },
  WA: {
    label: "WA",
    key: "wa",
    name: "Washington",
    dl_validation: "^[aA-zZ]{1,7}*?d{3}[aA-zZ]{0,2}$",
  },
  WV: {
    label: "WV",
    key: "wv",
    name: "West Virginia",
    dl_validation: "^[aA-zZ]d{6}$",
  },
  WI: {
    label: "WI",
    key: "wi",
    name: "Wisconsin",
    dl_validation: "^[aA-zZ]d{13}$",
  },
  WY: { label: "WY", key: "wy", name: "Wyoming", dl_validation: "^d{6}$" },
};
