"""changed event expenses to one to many

Revision ID: 234e186ac2cd
Revises: 509ecf895355
Create Date: 2026-07-14 16:44:09.974404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234e186ac2cd'
down_revision: Union[str, Sequence[str], None] = '509ecf895355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('expenses_event_id_key'), 'expenses', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('expenses_event_id_key'), 'expenses', ['event_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
