"""added timestamps to groups

Revision ID: 3a2b8487481a
Revises: 11ce9749882c
Create Date: 2026-07-10 19:40:04.521431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a2b8487481a'
down_revision: Union[str, Sequence[str], None] = '11ce9749882c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('groups', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'updated_at')
    op.drop_column('groups', 'created_at')
    # ### end Alembic commands ###
