"""added expenses table

Revision ID: 509ecf895355
Revises: 3a2b8487481a
Create Date: 2026-07-14 16:25:06.208273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '509ecf895355'
down_revision: Union[str, Sequence[str], None] = '3a2b8487481a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('uuid', sa.String(length=36), nullable=False))
    op.add_column('expenses', sa.Column('title', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('description', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('expenses', sa.Column('amount', sa.Float(), nullable=False))
    op.add_column('expenses', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('expenses', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('expenses', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_expenses_title'), 'expenses', ['title'], unique=False)
    op.create_index(op.f('ix_expenses_uuid'), 'expenses', ['uuid'], unique=True)
    op.create_unique_constraint(None, 'expenses', ['event_id'])
    op.create_foreign_key(None, 'expenses', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'expenses', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='unique')
    op.drop_index(op.f('ix_expenses_uuid'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_title'), table_name='expenses')
    op.drop_column('expenses', 'event_id')
    op.drop_column('expenses', 'owner_id')
    op.drop_column('expenses', 'created_at')
    op.drop_column('expenses', 'amount')
    op.drop_column('expenses', 'date')
    op.drop_column('expenses', 'description')
    op.drop_column('expenses', 'title')
    op.drop_column('expenses', 'uuid')
    # ### end Alembic commands ###
