name: PR Gate - Unit Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "PG_DB=${{ secrets.PG_DB }}" >> .env
          echo "PG_DB_USER=${{ secrets.PG_DB_USER }}" >> .env
          echo "PG_DB_PASS=${{ secrets.PG_DB_PASS }}" >> .env
          echo "PG_DB_HOST=${{ secrets.PG_DB_HOST }}" >> .env
          echo "PG_DB_PORT=${{ secrets.PG_DB_PORT }}" >> .env
          echo "ENVIRONMENT=${{ secrets.ENVIRONMENT }}" >> .env
          echo "WATCHTOWER_WEBHOOK=${{ secrets.WATCHTOWER_WEBHOOK }}" >> .env

      - name: Spin up Docker Compose environment
        run: docker compose up -d

      - name: Wait for Database to initialize
        run: sleep 10

      - name: Run Database Migrations
        run: docker compose exec -T api alembic upgrade head

      - name: Run Unit Tests
        run: docker compose exec -T api pytest

      - name: Shut down environment
        if: always()
        run: docker compose down -v
